export enum FormationCourseTagEnum {
  SoftwareDevelopment = 'software-development',
  MicrosoftTechnologies = 'microsoft-technologies',
  CSharp = 'csharp',
  DotNet = 'dotnet',
  Kubernetes = 'kubernetes',
  DockerContainer = 'docker-container',
  AzureCloud = 'azure-cloud',
  SoftwareTesting = 'software-testing',
  TDD = 'tdd',
  Agile = 'agile',
  Scrum = 'scrum',
  GoogleTechnologies = 'google-technologies',
  Golang = 'golang',
  DatabaseManagement = 'database-management',
  SOLID = 'solid',
  DesignPattern = 'design-pattern',
  ApacheTechnologies = 'apache-technologies',
  Kafka = 'kafka',
  CICD = 'ci/cd',
  DevOps = 'devops',
  GitGithub = 'git-github',
  Linux = "linux",
  Python = "python",
}
