export enum PublishNameEnum {
  CasaDoCodigo = 'Casa Do Código',
  Novatec = 'Novatec',
  Packts = 'Packts',
  Elsevier = 'Elsevier',
  AltaBooks = 'Alta Books',
  Bookman = 'Bookman',
  MicrosoftPress = 'Microsoft Press',
  Wrox = 'Wrox',
  MakronBooks = 'Makron Books',
  VisualBooks = 'Visual Books',
  CienciaModerna = 'Ciência Moderna',
  Campus = 'Campus',
  PortfolioPenguin = 'Portfolio Penguin',
  DCComics = 'DC Comics',
}
