allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2200.1'
  - '@angular-devkit/core@22.0.1'
  - '@angular-devkit/schematics@22.0.1'
  - '@angular/cli@22.0.1'
  - '@schematics/angular@22.0.1'
  - '@angular-devkit/build-angular@22.0.1'
  - '@angular-devkit/build-webpack@0.2200.1'
  - '@angular/build@22.0.1'
  - '@angular/common@22.0.1'
  - '@angular/compiler-cli@22.0.1'
  - '@angular/compiler@22.0.1'
  - '@angular/core@22.0.1'
  - '@angular/platform-browser-dynamic@22.0.1'
  - '@angular/platform-browser@22.0.1'
  - '@angular/router@22.0.1'
  - '@ngtools/webpack@22.0.1'
  - '@typescript/typescript-aix-ppc64@7.0.2'
  - '@typescript/typescript-darwin-arm64@7.0.2'
  - '@typescript/typescript-darwin-x64@7.0.2'
  - '@typescript/typescript-freebsd-arm64@7.0.2'
  - '@typescript/typescript-freebsd-x64@7.0.2'
  - '@typescript/typescript-linux-arm64@7.0.2'
  - '@typescript/typescript-linux-arm@7.0.2'
  - '@typescript/typescript-linux-loong64@7.0.2'
  - '@typescript/typescript-linux-mips64el@7.0.2'
  - '@typescript/typescript-linux-ppc64@7.0.2'
  - '@typescript/typescript-linux-riscv64@7.0.2'
  - '@typescript/typescript-linux-s390x@7.0.2'
  - '@typescript/typescript-linux-x64@7.0.2'
  - '@typescript/typescript-netbsd-arm64@7.0.2'
  - '@typescript/typescript-netbsd-x64@7.0.2'
  - '@typescript/typescript-openbsd-arm64@7.0.2'
  - '@typescript/typescript-openbsd-x64@7.0.2'
  - '@typescript/typescript-sunos-x64@7.0.2'
  - '@typescript/typescript-win32-arm64@7.0.2'
  - '@typescript/typescript-win32-x64@7.0.2'
  - typescript@7.0.2
