import { Pipe, PipeTransform } from '@angular/core';

const TAG_LABELS: Record<string, string> = {
  'software-development': 'Software Development',
  'csharp': 'C#',
  'dotnet': '.NET',
  'javascript': 'JavaScript',
  'typescript': 'TypeScript',
  'golang': 'Golang',
  'artificial-intelligence': 'AI',
  'database': 'Database',
  'nosql': 'NoSQL',
  'mongodb': 'MongoDB',
  'sql': 'SQL',
  'azure': 'Azure',
  'microsoft': 'Microsoft',
  'agile': 'Agile',
  'scrum': 'Scrum',
  'design-pattern': 'Design Patterns',
  'solid': 'SOLID',
  'tdd': 'TDD',
  'testing': 'Testing',
  'refactor': 'Refactoring',
  'clean-code': 'Clean Code',
  'domain-driven-design': 'DDD',
  'event-driven-architecture': 'EDA',
  'rust': 'Rust',
  'network': 'Network',
  'operational-system': 'OS',
  'linux': 'Linux',
  'graph-algorithms': 'Graph Algorithms',
  'oo': 'OOP',
  'microservices': 'Microservices',
  'kubernetes': 'Kubernetes',
  'docker': 'Docker',
  'docker-container': 'Docker',
  'devops': 'DevOps',
  'python': 'Python',
  'cplusplus': 'C++',
  'security': 'Security',
  'uml': 'UML',
  'algorithms': 'Algorithms',
  'culture': 'Culture',
  'business': 'Business',
  'react': 'React',
  'kafka': 'Kafka',
  'github': 'GitHub',
  'copilot': 'Copilot',
  'communication': 'Communication',
  'leadership': 'Leadership',
  'cripto': 'Cryptography',
  'blockchain': 'Blockchain',
  'sustainability': 'Sustainability',
  'architecture': 'Architecture',
  'messagerie': 'Messaging',
  'amqp': 'AMQP',
  'monitoring': 'Monitoring',
  'prometheus': 'Prometheus',
  'grafana': 'Grafana',
  'blazor': 'Blazor',
  'sqlserver': 'SQL Server',
  'postgres': 'PostgreSQL',
  'cloud-computing': 'Cloud',
  'entra-id': 'Entra ID',
  'jira': 'Jira',
  'neo4j': 'Neo4j',
  'graph': 'Graph DB',
  'node': 'Node.js',
  'http': 'HTTP',
  'lgpd': 'LGPD',
  'aws': 'AWS',
  'dns': 'DNS',
  'all': 'All',
  'angular': 'Angular',
  'vue': 'Vue.js',
  'hash': 'Hashing',
  'git': 'Git',
  'versioning': 'Versioning',
  'az303': 'AZ-303',
  'az304': 'AZ-304',
  'chatbot': 'Chatbot',
  'gpt': 'GPT',
  'google': 'Google',
  'c4model': 'C4 Model',
  'logic': 'Logic',
  'dart': 'Dart',
  'redis': 'Redis',
  'cache': 'Cache',
  'java': 'Java',
  'digital-ocean': 'DigitalOcean',
  'dapper': 'Dapper',
  'orm': 'ORM',
  'software-testing': 'Software Testing',
  'microsoft-technologies': 'Microsoft',
  'azure-cloud': 'Azure Cloud',
  'google-technologies': 'Google Tech',
  'database-management': 'Databases',
  'apache-technologies': 'Apache',
  'ci-cd': 'CI/CD',
  'git-github': 'Git & GitHub',
  'fullstack': 'Full-Stack',
  'networking': 'Networking',
};

export function slugToLabel(slug: string): string {
  if (TAG_LABELS[slug]) return TAG_LABELS[slug];
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

@Pipe({
  name: 'tagLabel',
  standalone: true,
})
export class TagLabelPipe implements PipeTransform {
  transform(slug: string): string {
    return slugToLabel(slug);
  }
}
